// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGcp7sCryMZ5kEPP2mFNcCbD8j4lAEoF0',
    appId: '1:889755325501:web:b6b6c6f2113019455d8654',
    messagingSenderId: '889755325501',
    projectId: 'bsafe-b5232',
    authDomain: 'bsafe-b5232.firebaseapp.com',
    storageBucket: 'bsafe-b5232.appspot.com',
    measurementId: 'G-G76GDETVSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9XyIq6Q09ipj16TeCpQ8i91ObmJGrDf4',
    appId: '1:889755325501:android:8a625315928150c15d8654',
    messagingSenderId: '889755325501',
    projectId: 'bsafe-b5232',
    storageBucket: 'bsafe-b5232.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVs96b8ezhZcf74JWQPjZBnH0H4KyJe1k',
    appId: '1:889755325501:ios:bb36f4b303e748845d8654',
    messagingSenderId: '889755325501',
    projectId: 'bsafe-b5232',
    storageBucket: 'bsafe-b5232.appspot.com',
    iosBundleId: 'com.example.bsafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVs96b8ezhZcf74JWQPjZBnH0H4KyJe1k',
    appId: '1:889755325501:ios:bb36f4b303e748845d8654',
    messagingSenderId: '889755325501',
    projectId: 'bsafe-b5232',
    storageBucket: 'bsafe-b5232.appspot.com',
    iosBundleId: 'com.example.bsafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGcp7sCryMZ5kEPP2mFNcCbD8j4lAEoF0',
    appId: '1:889755325501:web:aa621392eec7f46c5d8654',
    messagingSenderId: '889755325501',
    projectId: 'bsafe-b5232',
    authDomain: 'bsafe-b5232.firebaseapp.com',
    storageBucket: 'bsafe-b5232.appspot.com',
    measurementId: 'G-XZ2SBP9GKS',
  );

}